security:
    encoders:
        App\Entity\Core\Usuario:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Core\Usuario
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_dashboard

            logout:
                path: app_logout
                target: app_login

    access_control:
        # Permite acessar login sem estar logado
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Permite acessar o cadastro de usuário
        - { path: ^/usuario/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Bloqueia tudo o resto
        - { path: ^/, roles: ROLE_USER }
